### ISSUE TITLE
spieler.einsen nicht auf Null gesetzt wenn weiter() gecallt wird. 

### ISSUE THREAD

**Issue by klunkean** [papr/schocken#15]
Siehe `tests/test_wuerfeln.py`, Funktion `test_eins_beiseite_dann_weiter(spieler)`.
Letzter `assert` schlägt fehl:

https://github.com/papr/schocken/blob/97f44c2a3b0380d836432fa3b494717c73159849/tests/test_wuerfeln.py#L41

**Comment by CGentsch** [comment]
fix liegt im master branch
